/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.2 at Sat Dec 29 16:04:41 2018. */

#include "drone.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Motors_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Motors, motor_DL, motor_DL, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, Motors, motor_DR, motor_DL, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, Motors, motor_R, motor_DR, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, Motors, motor_L, motor_R, 0),
    PB_LAST_FIELD
};

const pb_field_t DroneState_fields[13] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, DroneState, roll, roll, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, DroneState, pitch, roll, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, DroneState, yaw, pitch, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, DroneState, acc_x, yaw, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, DroneState, acc_y, acc_x, 0),
    PB_FIELD(  6, INT32   , REQUIRED, STATIC  , OTHER, DroneState, acc_z, acc_y, 0),
    PB_FIELD(  7, INT32   , REQUIRED, STATIC  , OTHER, DroneState, gyro_x, acc_z, 0),
    PB_FIELD(  8, INT32   , REQUIRED, STATIC  , OTHER, DroneState, gyro_y, gyro_x, 0),
    PB_FIELD(  9, INT32   , REQUIRED, STATIC  , OTHER, DroneState, gyro_z, gyro_y, 0),
    PB_FIELD( 10, INT32   , REQUIRED, STATIC  , OTHER, DroneState, mag_x, gyro_z, 0),
    PB_FIELD( 11, INT32   , REQUIRED, STATIC  , OTHER, DroneState, mag_y, mag_x, 0),
    PB_FIELD( 12, INT32   , REQUIRED, STATIC  , OTHER, DroneState, mag_z, mag_y, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
