# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drone.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='drone.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0b\x64rone.proto\"N\n\x06Motors\x12\x10\n\x08motor_DL\x18\x01 \x02(\r\x12\x10\n\x08motor_DR\x18\x02 \x02(\r\x12\x0f\n\x07motor_R\x18\x03 \x02(\r\x12\x0f\n\x07motor_L\x18\x04 \x02(\r\"\xc0\x01\n\nDroneState\x12\x0c\n\x04roll\x18\x01 \x02(\x02\x12\r\n\x05pitch\x18\x02 \x02(\x02\x12\x0b\n\x03yaw\x18\x03 \x02(\x02\x12\r\n\x05\x61\x63\x63_x\x18\x04 \x02(\x05\x12\r\n\x05\x61\x63\x63_y\x18\x05 \x02(\x05\x12\r\n\x05\x61\x63\x63_z\x18\x06 \x02(\x05\x12\x0e\n\x06gyro_x\x18\x07 \x02(\x05\x12\x0e\n\x06gyro_y\x18\x08 \x02(\x05\x12\x0e\n\x06gyro_z\x18\t \x02(\x05\x12\r\n\x05mag_x\x18\n \x02(\x05\x12\r\n\x05mag_y\x18\x0b \x02(\x05\x12\r\n\x05mag_z\x18\x0c \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MOTORS = _descriptor.Descriptor(
  name='Motors',
  full_name='Motors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='motor_DL', full_name='Motors.motor_DL', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor_DR', full_name='Motors.motor_DR', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor_R', full_name='Motors.motor_R', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='motor_L', full_name='Motors.motor_L', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=93,
)


_DRONESTATE = _descriptor.Descriptor(
  name='DroneState',
  full_name='DroneState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='roll', full_name='DroneState.roll', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='DroneState.pitch', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='DroneState.yaw', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acc_x', full_name='DroneState.acc_x', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acc_y', full_name='DroneState.acc_y', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='acc_z', full_name='DroneState.acc_z', index=5,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gyro_x', full_name='DroneState.gyro_x', index=6,
      number=7, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gyro_y', full_name='DroneState.gyro_y', index=7,
      number=8, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gyro_z', full_name='DroneState.gyro_z', index=8,
      number=9, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mag_x', full_name='DroneState.mag_x', index=9,
      number=10, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mag_y', full_name='DroneState.mag_y', index=10,
      number=11, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mag_z', full_name='DroneState.mag_z', index=11,
      number=12, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=288,
)

DESCRIPTOR.message_types_by_name['Motors'] = _MOTORS
DESCRIPTOR.message_types_by_name['DroneState'] = _DRONESTATE

Motors = _reflection.GeneratedProtocolMessageType('Motors', (_message.Message,), dict(
  DESCRIPTOR = _MOTORS,
  __module__ = 'drone_pb2'
  # @@protoc_insertion_point(class_scope:Motors)
  ))
_sym_db.RegisterMessage(Motors)

DroneState = _reflection.GeneratedProtocolMessageType('DroneState', (_message.Message,), dict(
  DESCRIPTOR = _DRONESTATE,
  __module__ = 'drone_pb2'
  # @@protoc_insertion_point(class_scope:DroneState)
  ))
_sym_db.RegisterMessage(DroneState)


# @@protoc_insertion_point(module_scope)
